[package]
name = "mccraft_importer"
version = "0.1.0"
authors = ["bobtwinkles <srkoser+github@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
mccraft_core = { path = "../mccraft_core" }
fxhash = "0.2"
log = "0.4"
env_logger = "0.5"
string-interner = "0.7"
